name: libstackmate
description: stackmate-core (rust) ffi
version: 0.12.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.libstackmate
        pluginClass: LibStackmatePlugin
      ios:
        pluginClass: LibStackmatePlugin
