// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sats/model/blockchain.dart';
import 'package:sats/model/fees.dart';
import 'package:sats/model/node.dart';
import 'package:sats/model/pin.dart';
import 'package:sats/model/preferences.dart';
import 'package:sats/model/tor.dart';
import 'package:sats/model/transaction.dart';
import 'package:sats/model/wallet.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BlockchainClassAdapter());
    registerAdapter(FeesClassAdapter());
    registerAdapter(NodeClassAdapter());
    registerAdapter(PinClassAdapter());
    registerAdapter(PreferencesClassAdapter());
    registerAdapter(TorClassAdapter());
    registerAdapter(TransactionClassAdapter());
    registerAdapter(WalletClassAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BlockchainClassAdapter());
    registerAdapter(FeesClassAdapter());
    registerAdapter(NodeClassAdapter());
    registerAdapter(PinClassAdapter());
    registerAdapter(PreferencesClassAdapter());
    registerAdapter(TorClassAdapter());
    registerAdapter(TransactionClassAdapter());
    registerAdapter(WalletClassAdapter());
  }
}
